### PR TITLE
Make ssh_public_key_file optional

### PR DESCRIPTION
**Pull request by Toilal**
This field doesn't seems to be mandatory for those using additional_users features

### CODE REVIEW

**Comment by sudermanjr** [comment]
That key is used for the root `ubuntu` user and is mandatory. You don't have to keep the private key around ( we frequently discard it ), but it is required for bootstrapping.

**Comment by ivanfetch-fw** [comment]
Hello @Toilal, thank you for this suggestion.

Would you mind running `make` which will use Docker to run a specific version of terraform-docs to regenerate README.md, with your updates to `inputs.tf`? There is a bit more detail in [the contributing file](https://github.com/FairwindsOps/terraform-bastion/blob/master/CONTRIBUTING.md).

**Comment by Toilal** [comment]
> Hello @Toilal, thank you for this suggestion.
> 
> Would you mind running `make` which will use Docker to run a specific version of terraform-docs to regenerate README.md, with your updates to `inputs.tf`? There is a bit more detail in [the contributing file](https://github.com/FairwindsOps/terraform-bastion/blob/master/CONTRIBUTING.md).

Done :)

**Review by ivanfetch-fw — APPROVED** [review]
Thank you again for this fix.

**Pull request merged**
