### PR TITLE
add additional_script_files to be loaded on EC2 instance creation

### PR DESCRIPTION
**Pull request by Toilal**
This can be used to execute additional commands from files available in terraform module directory.

### CODE REVIEW

**Comment by ivanfetch-fw** [comment]
Hello,

Thank you for this contribution.

Would you mind describing your use case for this feature a bit more?

We favor editing the in-module `bastion-userdata.tmpl` script for changes that apply to all bastions, or using the `additional_user_data` Terraform input to augment user-data from code that calls the module.

If you are looking to add user-data after the `additional_users` have been created on the bastion, we could add a new Terraform input such as `additional_user_data_end` to be executed last - this would keep more inline with our current inputs and design.

Thanks again, for your suggestions.

**Comment by Toilal** [comment]
> If you are looking to add user-data after the `additional_users` have been created on the bastion, we could add a new Terraform input such as `additional_user_data_end` to be executed last - this would keep more inline with our current inputs and design.

That's it, i'll do.

**Comment by Toilal** [comment]
It seems easier to reference external script files to be provisionned than inlining scripts inside terraform configuration files. That's highly subjective of course, but providing both way of doing could be an option.

**Comment by Toilal** [comment]
I'm closing this PR in favor of #63. Local script files can injected using `file()` function and existing inputs.

```terraform
additional_user_data_end = join("\n", [
  file("${path.root}/scripts/psql-client.sh"),
  file("${path.root}/scripts/openvpn.sh")
])
```

**Pull request closed without merging**
